sdiehl/write-you-a-haskell

- basics.md
- evaluation.md
- hindley_milner.md
- introduction.md
- lambda_calculus.md
- parsers.md
- path.md
- type_systems.md
Thank you so much for this book; I can tell it's going to help me learn an enormous amount this year.
Please accept this PR to make the reading a little more comfortable for myself and other apostrophe pedants. :)
> Apostrophe pedantry (fixes #9 and other similar occurrences)

- evaluation.md
Same caveats as #18 apply... Also see #19 and #20 for which I made no related changes.
> Various fixes in `evaluation.md`

- 001_basics.md
Noticed this was missing a code fence while reading :)
> Added code fence to *>

- 001_basics.md
@sdiehl, see if this pull request is acceptable.
Thank you for making this available!
> Replace "contagious" with "contiguous"

- 001_basics.md
We define Either but pattern-match on Maybe.
Changed the definition.
> Either -> Maybe in Basics

- 001_basics.md
Typo fixes, grammatical edits, and some stylistic adjustments (all of which hopefully clarify things!)
> Grammar fixes (001-basics)

- chapter3/calc/Pretty.hs
- chapter3/calc/calc.cabal
- chapter7/poly/Infer.hs
- chapter7/poly/Main.hs
- chapter7/poly/Type.hs
calc doesn't build (for me) without the first two commits.
poly has some type inference bugs -- see commit message.
However you fix it, the change should be mirrored in 006_hindley_milner.md.
BTW, why does that correspond to code in chapter7/ ?
Thanks for your very nice work!
You made me finally create a github account...
> make calc build and fix poly

- chapter7/poly/Infer.hs
- chapter7/poly_constraints/Infer.hs
Guess the first commit is beyond dispute,
the others might remove machinery that you need later on.
> Simplify poly and poly_constraints

- 000_introduction.md
- 001_basics.md
- 002_parsers.md
- chapter3/calc/Eval.hs
- chapter3/parsec.hs
Some proposed changes to the first four chapters and the accompanying code.
Please also have a look at my 'remarks' branch where I marked lines that I felt might be improved without having concrete suggestions. I plan to continue committing remarks to that branch, so you might want to track it.
> more changes

- 003_lambda_calculus.md
- 004_type_systems.md
Hi, Would you check two commits:
* greek character problem (003_lambda_calculus.md) : issue #49
* a little typo (004_type_systems.md)
I send a pull request accordance with "Simple Fixes" scheme.
(I have not yet able to successfully install the pandoc.)
>  Fix Greek character and existential quantifier

- 004_type_systems.md
- chapter5/stlc/Check.hs
> changes to the Type Systems chapter

- 001_basics.md
- 002_parsers.md
- 005_evaluation.md
- chapter6/io.hs
- chapter6/phoas.hs
there is also new stuff in the remarks branch
> several small changes

- 003_lambda_calculus.md
- CONTRIBUTORS.md
Fixing typos and grammatical infelicities on the way while reading.
> Small fixes

- 006_hindley_milner.md
Small and not so small changes to the beginning of chapter 7.
> changes to the Hindley-Milner Inference chapter

- 008_extended_parser.md
I just fixed what I found when glossing over the newest article in the series (I'm not yet at that point, so I did not want to spoil the fun by carefully reading through everything).
Cheers
> Fixed a few typos

- chapter3/calc/Parser.hs
Changed "Infix" to "Prefix" in comment.
> "Infix" --> "Prefix" in comment

- 000_introduction.md
The role of the first few snippets is not completely clear from the text, I think it would be good to give some more context.
> Some edits in "Code generation" section

- 004_type_systems.md
TArr is referenced in the code a few times but is never defined. In the code it is part of the Type datatype, so I added it there.
> Added missing TArr to the type definition

- 004_type_systems.md
- chapter5/calc_typed/Check.hs
Just a small error I found while reading Chapter 5.
> Chapter 5: Fixed Type Mismatch message for If.

- 006_hindley_milner.md
- 008_extended_parser.md
- chapter9/provenance/Pretty.hs
Spotted a couple of typos (or at least I think they are).
Thanks for this superb work!
> Spotted a couple of typos
